/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.edegier.pwndclient;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class PwndAPITest {
    @Test
    void testHaveIBeenPwned() {
        PwndAPI pwndAPI = new PwndAPI(new MockPwndClient());

        assertTrue(pwndAPI.haveIBeenPwned("password"), "should return 'true'");
    }
}
